package com.industria.coordinacion.ui

import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.sistema.distribuido.network.prefecto.IndustrialTheme
import com.sistema.distribuido.network.prefecto.IndustrialCard
import com.sistema.distribuido.network.prefecto.IndustrialActionButton
import com.sistema.distribuido.network.prefecto.IndustrialTextField

@Composable
fun ArucoGeneratorTab(
    onGenerateAruco: (String) -> Unit,
    onUseWithLaser: (String) -> Unit = {},
    modifier: Modifier = Modifier
) {
    var arucoId by remember { mutableStateOf("1") }
    var sizePx by remember { mutableStateOf("250") }
    var isGenerated by remember { mutableStateOf(false) }

    LazyColumn(
        modifier = modifier.fillMaxSize().padding(horizontal = 16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        item {
            IndustrialCard("Generador de Marcadores", Icons.Default.QrCode) {
                IndustrialTextField(valor = arucoId, onValueChange = { arucoId = it }, label = "ID del Marcador (0-99)")
                Spacer(Modifier.height(8.dp))
                IndustrialTextField(valor = sizePx, onValueChange = { sizePx = it }, label = "Tamaño de Impresión (PX)")
                Spacer(Modifier.height(16.dp))
                IndustrialActionButton(
                    texto = "Generar Pattern", 
                    icono = Icons.Default.Autorenew, 
                    onClick = { 
                        isGenerated = true
                        onGenerateAruco("ID:$arucoId|SIZE:$sizePx")
                    }
                )
            }
        }

        if (isGenerated) {
            item {
                IndustrialCard("Vista Previa del Marcador", Icons.Default.Visibility) {
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(200.dp)
                            .background(Color.White, androidx.compose.foundation.shape.RoundedCornerShape(4.dp))
                            .padding(16.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        // Simulación visual de un ArUco (Cuadrado negro con ID en medio para debug)
                        Box(Modifier.size(150.dp).background(Color.Black), contentAlignment = Alignment.Center) {
                            Box(Modifier.size(120.dp).background(Color.White), contentAlignment = Alignment.Center) {
                                Text("ID: $arucoId", fontWeight = FontWeight.Black, fontSize = 24.sp, color = Color.Black)
                            }
                        }
                    }
                    Spacer(Modifier.height(12.dp))
                    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        IndustrialActionButton(
                            texto = "Enviar a Láser", 
                            icono = Icons.Default.FlashOn, 
                            modifier = Modifier.weight(1f),
                            colorFondo = IndustrialTheme.Advertencia,
                            onClick = { onUseWithLaser("ARUCO_$arucoId") }
                        )
                        IndustrialActionButton(
                            texto = "Guardar", 
                            icono = Icons.Default.Save, 
                            modifier = Modifier.weight(1f),
                            colorFondo = IndustrialTheme.Exito,
                            onClick = { isGenerated = false }
                        )
                    }
                }
            }
        }

        item {
            IndustrialCard("Diccionarios Disponibles", Icons.Default.List) {
                Text("• DICT_4X4_50 (Optimizado)", color = IndustrialTheme.TextoPrincipal, fontSize = 12.sp)
                Text("• DICT_5X5_100 (Alta Precisión)", color = IndustrialTheme.TextoSecundario, fontSize = 12.sp)
                Text("• DICT_6X6_250 (Máximo Rango)", color = IndustrialTheme.TextoSecundario, fontSize = 12.sp)
            }
        }
    }
}
